//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjerciciosPropuestos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public int codventa { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> codcliente { get; set; }
        public Nullable<int> codproducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> totalventa { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
